Feature/router optional params
rdkcentral/Lightning-SDK pull request #363
Opened 2022-12-02 07:20 UTC by sandeep-vedam

Added support for optional parameters another approach

2022-12-02 09:47 UTC, ricardo-a-alves-alb requested changes

2022-12-02 09:47 UTC, ricardo-a-alves-alb commented on src/Router/index.js
> +  console.log('ABCDE Route to be navigated =>', route)
Forgotten?

2022-12-02 09:47 UTC, ricardo-a-alves-alb commented on src/Router/index.js
> +  console.log('ABCDE request information =>', request)
Forgotten?

2022-12-02 09:47 UTC, ricardo-a-alves-alb commented on src/Router/index.js
> +  console.log('ABCDE Result beforenavigate =>', result)
Forgotten?

2022-12-02 09:47 UTC, ricardo-a-alves-alb commented on src/Router/index.js
> +      console.log('ABCDE resolve hash change', request)
Forgotten?

2022-12-02 09:47 UTC, ricardo-a-alves-alb commented on src/Router/index.js
> +      console.log('ABCDE router path before value from hash =>', routerPath, hash)
Forgotten?

2022-12-02 09:47 UTC, ricardo-a-alves-alb commented on src/Router/index.js
> +      console.log('ABCDE url parameters =>', urlParams)
Forgotten?

2022-12-02 09:47 UTC, ricardo-a-alves-alb commented on src/Router/utils/route.js
> +        // console.log("ABC router is matching =>", routePart, hashPart, false)
Forgotten?

2022-12-02 13:20 UTC, sandeep-vedam commented
Hey @ricardo-a-alves-alb 
That was a mistake.
Removed all console messages now. :-)

2022-12-14 09:52 UTC, sandeep-vedam commented
As the implementation of this PR is done in #362 , closing this PR

2022-12-14 09:52 UTC, closed without merging